### ISSUE TITLE
Replace ' by " (and reciprocally)

### ISSUE THREAD

**Issue by marmotz** [lexand/enclosing-jidea-plugin#4]
It would be nice if we could select a string like `'a string'`, type `"` and get `"a string"`, no ?

Maybe you should check if current selection have enclosing chars at the start and the end and replace it by current char ?

**Comment by lexand** [comment]
I will think about this idea.

**Comment by marmotz** [comment]
Closed because it's done ?

**Comment by lexand** [comment]
Settings -> Editor -> General -> Smart Keys

select checkbox "Surround selection on typing quote or brace"

https://blog.codeleak.pl/2014/06/how-to-surround-text-with-quote-in.html

Does it work for you ?

**Comment by marmotz** [comment]
yes it's working
