### ISSUE TITLE
Plugin incompatible with Pycharm 2020.1

### ISSUE THREAD

**Issue by mojeto** [lexand/enclosing-jidea-plugin#6]
When updating my Pycharm from 2019.3.4 to 2020.1 (PY-201.6668.115) I get `Plugin incompatible with the new build found: Enclosing Plugin` error message.
![image](https://user-images.githubusercontent.com/5433957/80039953-1df82880-854d-11ea-816f-0691287f8d4b.png)

**Comment by lexand** [comment]
Thanks, @mojeto 

I am working on it

**Comment by lexand** [comment]
After some learning of new API I may say this is the last days of this plugin.
I do not see any reason to support it, built-in analog is completely cover plugin functionality.

But I still thinking about rewriting to 2020.1 API...

**Comment by mojeto** [comment]
You right, the functionality is there even without your plugin. 
Your plugin made my work easier. Thank you for your work.

**Comment by lexand** [comment]
I decided I will not rewrite plugin to support 2020.1 API
